### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by TalepWOG** [Litzuck/lol-spectator-overlay-client#10]
Hi, tell me, does the software only work in 5v5, I tried to make it work (I was a spectator) and two friends were, redside and blueside, the rest we put bots, it turns out that nothing works, the timer does not start, the ban does not synchronize, nothing really happens, is this normal? Or did I do something wrong?

**Comment by Litzuck** [comment]
It works with any player count, but it doesn't support ANY bots in the game. So that was probably the problem.

**Comment by Litzuck** [comment]
I just looked into it there might have been an error in the release 2.0.2, that caused you problems, it should be fixed in the new release [2.0.3](https://github.com/Litzuck/lol-spectator-overlay-client/releases/tag/v2.0.3).
