### ISSUE TITLE
Is it possible to provide a 3BAN option

### ISSUE THREAD

**Issue by Khhd1** [Litzuck/lol-spectator-overlay-client#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Khhd1** [comment]
This is because the order of selection of champions is different for 3Ban and 5Ban

**Comment by Khhd1** [comment]
Ban PHASE display will also be changed

**Comment by Khhd1** [comment]
![屏幕截图](https://user-images.githubusercontent.com/82941693/118838373-35444980-b8f8-11eb-8516-a9a62d3c7e1c.png)
Picking in the right Jungle is to display errors, which may be carried out in accordance with the process of 5BAN

**Comment by Litzuck** [comment]
Thanks for pointing out this bug. I'll look into it.

**Comment by Litzuck** [comment]
Out of scope.
