### ISSUE TITLE
second view

### ISSUE THREAD

**Issue by Sky-CSC** [Litzuck/lol-spectator-overlay-client#15]
Do you think it is possible to create another display style ?
(Just with icon)
![Overlay_V2_Ban_Pick](https://user-images.githubusercontent.com/46931832/120919305-2364f380-c6b9-11eb-991b-16216398ffc2.png)

I formatted it with your base code (V2.0.3)
[Overlay_V2_Ban_Pick.zip](https://github.com/Litzuck/lol-spectator-overlay-client/files/6603947/Overlay_V2_Ban_Pick.zip)

**Comment by Litzuck** [comment]
Sorry for taking so long to answer. Sadly I don't have the time at the moment to create something like that, but I'll add the option of easily changing the layout on my todo list.

**Comment by Litzuck** [comment]
Out of scope.
