### ISSUE TITLE
2 pc problem

### ISSUE THREAD

**Issue by shinilee** [Litzuck/lol-spectator-overlay-client#17]
I tried the web server option but it doesn't work for me

web server provide from the program it work for local but when I tried to connect to streaming pc it doesn't read

I tried this link

http://[ip address]:8000

http://[ip address]:8000/?backend=ws://[ip address]:8000

**Comment by Litzuck** [comment]
Sorry for taking so long to answer. Currently this isn't possible, but I'll make sure this option is added in the next release.

**Comment by Litzuck** [comment]
Should work now with the newest version.
