### ISSUE TITLE
Change resolution to 1080p

### ISSUE THREAD

**Issue by challenger087** [Litzuck/lol-spectator-overlay-client#18]
Hi! The resolution is fixed at 1600x900, how i can change it to 1920x1080 ?
![Screenshot MFL (4)](https://user-images.githubusercontent.com/60705849/122945285-c5066900-d378-11eb-9e64-6e0f1dd35e27.png)

**Comment by ghost** [comment]
iirc, ctrl + shift + "+" to zoom in

**Comment by challenger087** [comment]
Fixed! thx for the help :)
