### ISSUE TITLE
Replays (Playing a recorded champ select)

### ISSUE THREAD

**Issue by katasuno** [Litzuck/lol-spectator-overlay-client#2]
Couldn't figure out how the reload feature works.
Do we have a chance to replay it so that we can test it?
![image](https://user-images.githubusercontent.com/62215083/109736869-204bfa00-7bd6-11eb-8199-794b60105f63.png)

**Comment by Litzuck** [comment]
The replay functionality isn't working in the current version, but it will be fixed in the next version, which should be out in 1-2 days.
With that version, every champion selection will be logged and can be replayed anytime.

**Comment by Litzuck** [comment]
Closed because of inactivity.

**Comment by cruxm4n** [comment]
reopen, the replay dont work

**Comment by marsultor** [comment]
@cruxm4n @Litzuck current status of this?
