### ISSUE TITLE
Automatically fetches champion loading images, splash arts and square icons from datadragon, which means that if a new champion is released it will automatically fetch the correct resources

### ISSUE THREAD

**Issue by venomx96** [Litzuck/lol-spectator-overlay-client#24]
This project use this setting.  https://github.com/RCVolus/lol-pick-ban-ui
It's a better option to have all champions updated.

As i can see in the non binary version, you tried the same with another API. The datadragon API is a Riot Official API. Always updated. You can too add skin selection maybe. This is 2 goods features very important for a really "professional" tool.

It also saves the space required to store all the images.

**Comment by overkido** [comment]
mais n tem como colocar as imagens desse ai, nesse outro dos champ eu não achei as imagens pra coloca na pasta.

**Comment by Litzuck** [comment]
Fixed with newest version
