### ISSUE TITLE
I can't find lol-esports-spectate-client.exe

### ISSUE THREAD

**Issue by YI-YEE** [Litzuck/lol-spectator-overlay-client#25]

**Comment by YI-YEE** [comment]
i am dum sorry i found it

**Comment by Sershi2k01** [comment]
Where is the file? I'm stupid and can't find it :(

**Comment by YI-YEE** [comment]
> Where is the file? I'm stupid and can't find it :(

https://github.com/Litzuck/lol-spectator-overlay-client/releases/tag/v2.1.0
