### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SulphideQiang** [Litzuck/lol-spectator-overlay-client#26]
After I pressed the button, I seemed to stay in the test screen, and there was no choice of BP. I need some help because I may not know if my operation is correct.
Moreover, the following error occurred after I clicked "star web serve"
![Snipaste_2021-10-11_00-39-57](https://user-images.githubusercontent.com/71908065/136705312-7a357837-b96e-441b-9107-0e1ec756e260.png)

**Comment by SulphideQiang** [comment]
It doesn't seem to read the client's ban / pick information

**Comment by Litzuck** [comment]
No further action required. Likely no issue anymore.
