### ISSUE TITLE
What is the intended way of using this?

### ISSUE THREAD

**Issue by Abarn279** [Litzuck/lol-spectator-overlay-client#29]
Hi, want to start off by saying I appreciate your work, I have a fork of this I'm working on for my for-fun amateur league. 

The actual tech works well, but I can't seem to find the intended way of porting this into OBS/streamlabs. There seems to be two options: 

1. Use a window capture of the electron overlay app (Issues: Transparency doesn't work because window capture doesn't capture transparency, and the app doesn't even work in this scenario unless windows has it active, I.e. you can't click into another app)
2. Use a browser source, and instead of giving it a local webserver URL, just give it the out build html from the build folder (this seems to work but it doesn't stretch to the size of the screen when pulling it into obs/streamlabs. My stream is capturing at 1080p so I don't think this should be an issue.

This is, of course, less of a question of OBS/Streamlabs, and moreso how this is meant to be used in the wild. 

- AB

**Comment by Abarn279** [comment]
Sorry, I think I answered my own question. I had forked an earlier version where you were still opening the UI in a browser window, now you're opening it in-browser on a local URL. This should be enough for me to fiddle with my own CSS and get this working for myself. Thank you!

**Comment by marsultor** [comment]
Great to hear. Hope you worked it out. Closing for now.
