### ISSUE TITLE
Doesn't show 1st BAN

### ISSUE THREAD

**Issue by TeeMo0n** [Litzuck/lol-spectator-overlay-client#33]
**Describe the bug**
I asked my friend to open a custom game with 9 bots and I joined as spectator. Even though he started banning, it doesn't show the 1st ban and starts from 2nd ban.
He followed the steps discirbed in "Usage" but this happend.

I am sorry I am not English native speaker and do not code so my discription may be bad. If you have any questions I would try my best to answer any of it.

**Screenshots**
![image](https://user-images.githubusercontent.com/106720639/171988309-8f4bfe67-0211-48de-8133-cdad14c012db.png)
![image](https://user-images.githubusercontent.com/106720639/171988322-5d8cf474-2ed0-44cd-a815-cb141e0dbb26.png)

**Desktop (please complete the following information):**
 - Tool version: 2.2.2
 - Legue Client Version:12.10

**Comment by Litzuck** [comment]
Adding bots to the lobby causes unexpected behaviour, that is why they are not supported. This shouldn't happen when there are no bots present in the game.
