### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by fonsua** [Litzuck/lol-spectator-overlay-client#4]
@Litzuck 
https://ibb.co/pKMDX34 link photo

when the other team chooses, they don't show me summoner spells. I don't know if it's a bug of mine or something wrong with the overlay.

please i need help because i have a tournament on saturday.
 thank you

**Comment by Litzuck** [comment]
Did you take part in the game or were you just a spectator? If it is the former, then i can't change anything, because i can't get the data for those summoner spells. The tool is supposed to be used only as a spectator, because of this some strange things might be happening if you are taking part in the game yourself.

**Comment by fonsua** [comment]
you're right, I was in the champion selection.

I just tried being a spectator right now and I'm doing well with summoner spells, sorry for the trouble.

Another doubt I have is that when it is 5 vs 4 or 4 vs 4 the overlay does not work since when the red team is choosing the champion it is shown on the blue side or simply when the other team has a double choice only the 1st is shown but at the choose the second is empty. MAYBE THE OVERLAY ONLY WORKS 5 VS 5 BUT IT IS MY DOUBT IF IT COULD WORK IN 4 VS 4 ALSO.
THANK YOU

**Comment by fonsua** [comment]
since I do not program I would like to know how to change the color of the timers instead of being red and blue to be able to change them to different colors, and if doing so also changes the color of the section where it says "ban phase 1 or 2", thank you for the help.

**Comment by Litzuck** [comment]
Currently those things are not supported, but in a few days there will be a new version that allows you to change the color and supports games with variable amount of players.

**Comment by Litzuck** [comment]
The new release, which incorporates some of the features you requested is now available.

**Comment by fonsua** [comment]
what a nice guy you are.
Thank you so much.

**Comment by fonsua** [comment]
@Litzuck 
https://ibb.co/WxQKyBy   here photo



There are some parts that do not focus well on the shampoo. I don't know if it would be asking you a lot if you could fix it, I tried but I couldn't find how to do it since I'm not a programmer.

**Comment by Litzuck** [comment]
There is a new release out, which should fix those bugs.

**Comment by marsultor** [comment]
@fonsua Do you still have problems? Otherwise I would close the issue.

**Comment by fonsua** [comment]
![change](https://user-images.githubusercontent.com/83319321/118004303-a066ac80-b349-11eb-9b33-24168c547497.JPG)

**Comment by fonsua** [comment]
![change](https://user-images.githubusercontent.com/83319321/118004456-c4c28900-b349-11eb-8d38-ff2bc142524c.JPG)
![Captur12](https://user-images.githubusercontent.com/83319321/118004460-c55b1f80-b349-11eb-8475-50bb7c2e73d1.JPG)

With what was posted at the beginning, everything is solved and with the new client the image bugs are already fixed, although some images in the champion selection have a lot of zoom but it would be fine, I suppose.
now I have another question, how could I change what it says "picking" and change it to something else? in the new version I can't find where it should be to be able to change it.

@marsultor @Litzuck

**Comment by Litzuck** [comment]
Sorry I overlooked your answer. I just published a new release that implements your requested feature.
