### ISSUE TITLE
App still use old Riot ID and edit summoner names was broken

### ISSUE THREAD

**Issue by socktow** [Litzuck/lol-spectator-overlay-client#40]
![image](https://github.com/Litzuck/lol-spectator-overlay-client/assets/14296959/6bcd544e-f200-4d39-a291-643b2a0aa115)
![image](https://github.com/Litzuck/lol-spectator-overlay-client/assets/14296959/20a177ec-6a58-4b73-888b-ffea61b869a5)

**Comment by Litzuck** [comment]
This is fixed now with the newest release the Riot IDs will be used.
