### ISSUE TITLE
Custom name bug error!

### ISSUE THREAD

**Issue by int1008** [Litzuck/lol-spectator-overlay-client#41]
**Describe the bug**
Custom summoner name bug error!

1. When did the error occurr
It happened in Champ Select.
2. What is the error
The error is the summoner name number one is on the summoner name two
3. How could this be reproduced
Tick on Enable Custom Summoner Names, then press save config!

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/21bc7d88-195e-4410-b63c-a29a6a7b7035)

**Desktop (please complete the following information):**
 - Tool version: 2.3.2
 - Legue Client Version: 14.14

**Comment by Litzuck** [comment]
Custom names should be fixed, if they don't appear immediately try to toggle them on and off.
