### ISSUE TITLE
Can Phase1 and Phase2 be designed as UI for professional events

### ISSUE THREAD

**Issue by Khhd1** [Litzuck/lol-spectator-overlay-client#5]
![1](https://user-images.githubusercontent.com/82941693/116507867-bc526300-a8f2-11eb-9263-b1ddb7edd345.png)
Colors like the bottom left and the bottom right, and the countdown on the top, are not always red and blue

**Comment by marsultor** [comment]
More customization might come in the future. For now you can head to /overlay-app/src/default/index.css and change --left-side-color:,  --right-side-color: and build it with custom colors. (alpha-webversion)

**Comment by Litzuck** [comment]
I don't quite understand what you mean, but there is a new release, that contains some customization options.
