### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by Sky-CSC** [Litzuck/lol-spectator-overlay-client#8]
Hi, when I run the application then the overlay and on the riot client I run the custom game, I get these errors:
(index.html run on Mozilla Firefox)
- Uncaught Error: Cannot find module './18446744073709552000.png'
- Error: Cannot find module './18446744073709552000.png'

and the overlay doesn't show me anything (white screen).

Do you have any idea what this error means?
![Capture d’écran 2021-05-06 173449](https://user-images.githubusercontent.com/46931832/117325851-6866f180-ae91-11eb-9d06-255ce69e2b0c.png)

**Comment by Litzuck** [comment]
You have to run the .exe file. I clarified the Usage paragraph [here](https://github.com/Litzuck/lol-spectator-overlay-client#usage), just follow what is written there and everything should work.

**Comment by Sky-CSC** [comment]
That's what I was doing ^^.
I was testing with bot and that's why it wasn't working. 
I launched with just two accounts and it works.
(Thanks for the quick answer)

Just a small question. Maybe it's said, but I don't see it if the code has a license?

**Comment by Litzuck** [comment]
Thanks for pointing this out. I just added one, the project is now under the MIT License from the version 2.0.2 onward, which I just published.
